freebsd_instance:
  image_family: freebsd-12-1

task:
  install_script:
  - pkg install -y cmake perl5 bison flex
  script:
  - mkdir build
  - cd build
  - cmake .. -WITH_TESTS=1
  - cmake --build .
  test_script:
  - ctest