freebsd_instance:
  image_family: freebsd-12-1

task:
  only_if: only_if: $CIRRUS_BRANCH =~ 'pull/.*'
  install_script:
  - pkg install -y cmake
  script:
  - mkdir build
  - cd build
  - cmake .. -WITH_TESTS=1
  - cmake --build .
  test_script:
  - ctest